#spring:
#  elasticsearch:
#    rest:
#      uris: http://localhost:9200
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    timeout: 10000
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 10000
#        max-idle: 8
#        min-idle: 0
#      shutdown-timeout: 100
##    password: Ncsjw@1234
#  datasource:
#    dynamic:
#      primary: master
#      strict: false
#      datasource:
#        master:
#          driver-class-name: org.h2.Driver
##          schema: classpath:db/schema-h2.sql
##          data: classpath:db/data-h2.sql
##          url: jdbc:h2:file:/usr/local/h2/bdp-uas
#          username: root
#          password: root
#          url: jdbc:h2:file:E:\anshare\h2\data\bdp-uas
#        slaveNanchang:
#          url: jdbc:postgresql://156.11.1.248:5432/nanchang-fenting
#          username: anshare
#          password: Anshare.SQL
#          driver-class-name: org.postgresql.Driver
#          driver-class-name: com.pivotal.jdbc.GreenplumDriver
#          type: com.alibaba.druid.pool.DruidDataSource
#  h2:
#    console:
#      enabled: true
#      path: /h2/bdp-uas
#      settings:
#        web-allow-others: true
#    druid:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://156.11.1.208:3306/bdp_uas?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#      username: root
#      password: root
#      initialSize: 1
#      minIdle: 1
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      logAbandoned: true
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1
#      validationQueryTimeout: 10000
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: false
#      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      stat-view-servlet:
#        enabled: true
#        url-pattern: "/druid/*"
#        allow: 127.0.0.1
#        reset-enable: false
#        login-username: admin
#        login-password: admin

#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  typeAliasesPackage: com.anshare.bdp.uas.**.model
#  global-config:
#    id-type: 2
#    field-strategy: 2
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: false
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.anshare.bdp: debug
    com.alibaba.nacos.client.naming: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 40003
  tomcat:
    max-http-form-post-size: 52428800

file:
  dirPath: E:\anshare\
  savePath: E:\anshare\
#  dirPath: /usr/local/
#  savePath: /usr/local/resultFile/
